/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StrengthWeakness = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
});
export const MatchResponse = IDL.Record({
  'matchScore' : IDL.Nat,
  'advice' : IDL.Text,
  'missingKeywords' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'analyzeGeneral' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [StrengthWeakness],
      [],
    ),
  'analyzeMatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MatchResponse],
      [],
    ),
  'getAllStrengths' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getMatchScores' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))], []),
  'getRankedMatches' : IDL.Func([], [IDL.Vec(MatchResponse)], []),
  'getSuggestedJobs' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StrengthWeakness = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
  });
  const MatchResponse = IDL.Record({
    'matchScore' : IDL.Nat,
    'advice' : IDL.Text,
    'missingKeywords' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'analyzeGeneral' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [StrengthWeakness],
        [],
      ),
    'analyzeMatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [MatchResponse],
        [],
      ),
    'getAllStrengths' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getMatchScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
      ),
    'getRankedMatches' : IDL.Func([], [IDL.Vec(MatchResponse)], []),
    'getSuggestedJobs' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };